openapi: 3.1.0
info:
  title: Schemas of indices.get_index_template category
  description: Schemas of indices.get_index_template category
  version: 1.0.0
paths: {}
components:
  schemas:
    IndexTemplate:
      type: object
      properties:
        index_patterns:
          $ref: '_common.yaml#/components/schemas/Names'
        composed_of:
          description: |-
            An ordered list of component template names.
            Component templates are merged in the order specified, meaning that the last component template specified has the highest precedence.
          type: array
          items:
            $ref: '_common.yaml#/components/schemas/Name'
        template:
          $ref: '#/components/schemas/IndexTemplateSummary'
        version:
          $ref: '_common.yaml#/components/schemas/VersionNumber'
        priority:
          description: |-
            Priority to determine index template precedence when a new data stream or index is created.
            The index template with the highest priority is chosen.
            If no priority is specified the template is treated as though it is of priority 0 (lowest priority).
            This number is not automatically generated by OpenSearch.
          type: integer
          format: int64
        _meta:
          $ref: '_common.yaml#/components/schemas/Metadata'
        allow_auto_create:
          type: boolean
        data_stream:
          $ref: 'indices._common.yaml#/components/schemas/IndexTemplateDataStreamConfiguration'
      required:
        - index_patterns
      description: New index template definition to be simulated, if no index template name is specified.
    IndexTemplateSummary:
      type: object
      properties:
        aliases:
          description: |-
            Aliases to add.
            If the index template includes a `data_stream` object, these are data stream aliases.
            Otherwise, these are index aliases.
            Data stream aliases ignore the `index_routing`, `routing`, and `search_routing` options.
          type: object
          additionalProperties:
            $ref: 'indices._common.yaml#/components/schemas/Alias'
        mappings:
          $ref: '_common.mapping.yaml#/components/schemas/TypeMapping'
        settings:
          $ref: 'indices._common.yaml#/components/schemas/IndexSettings'
    IndexTemplateItem:
      type: object
      properties:
        name:
          $ref: '_common.yaml#/components/schemas/Name'
        index_template:
          $ref: '#/components/schemas/IndexTemplate'
      required:
        - index_template
        - name
